name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Dependencies
        run: |
          cd client
          npm ci
        env:
          NODE_ENV: production

      - name: Build Client
        run: |
          cd client
          npm run build
          npm run export
        env:
          NEXT_PUBLIC_SUPABASE_URL: 'https://uohjvwasdwenruhnvskn.supabase.co'
          NEXT_PUBLIC_SUPABASE_ANON_KEY: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVvaGp2d2FzZHdlbnJ1aG52c2tuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkyMDk5MjYsImV4cCI6MjA1NDc4NTkyNn0.acqU4ZfSwIhnsWrr24YYWiZwmY41i8yjjGlzkn1gdmA'
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
          NEXT_PUBLIC_BASE_PATH: '/shaip'

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: client/out
          branch: gh-pages